### ISSUE TITLE
Animated textures while holding Alt

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#100]
**Describe the bug**
Animated textures from walking, such as walking through grass, animates when holding alt and a direction key.

**To Reproduce**
1. Step into some tall grass
2. Hold alt and any arrow key/ WASD.

**Expected behavior**
For it not to be animated.

**Screenshots**
https://media.discordapp.net/attachments/652082895527346186/742461368996724958/grass.gif

**Context:**
 - Character Name: Charles
 - OS: Windows 10
 - Patch Version: 0.3.82
 - Game Build: 339

**Comment by phanxgames** [comment]
Fixed.
