### ISSUE TITLE
Construction Obstruction Quest NPC Bug

### ISSUE THREAD

**Issue by iEnvyU** [phanxgames/AetherStory#101]
**Describe the bug**
This bug is caused after accepting the quest and continuing to talk to each worker as they are fading away their name is still visible,

**To Reproduce**
1. Get the quest "Construction Obstruction"
2. Proceed to find each worker and turn in the quest
3. As the NPC starts to walk away keep your cursor over the NPC and follow its pathing and as they are vanishing you can still see their name

**Expected behavior**
As per turning quest into each npc they would walk away and vanish with their name vanishing with the npc

**Screenshots**

**Context:**
 - Envy
 - Windows 10
 - Patch: 0.3.85
 - Build: 351

**Additional context**
N/A

**Comment by phanxgames** [comment]
Did the name remain after the NPC disappeared? Was the name remaining always or just when you hovered over the location?

**Comment by CharlesIV** [comment]
Would this be a fair summary?

**Issue:**
After talking to one of the workers, they start walking and begin to fade out. You can follow the worker with your cursor as they fade out and the name still shows while hovering over their location even after the worker becomes completely faded out. Once the worker (entity) disappears the name disappears.

**Video**
https://cdn.discordapp.com/attachments/674835622313328670/747266700910657646/2020-08-23_21-28-15.mp4

**Possible Solution:**
Fade out the name along with the worker.

**Comment by phanxgames** [comment]
I am unsure if this is worth the effort involved if the name does eventually disappear after the NPC does.

But please clarify if Charles' description is what you are reporting. Thank you.

**Comment by iEnvyU** [comment]
@phanxgames Yes Charles made a fair summary of what I've reported nothing seems to be left out and the video is exactly what i saw <3

**Comment by phanxgames** [comment]
Okay. Thank you Envy!  If that is the issue, I will elect to not fix this at this time.
