### ISSUE TITLE
Arrow keys causing crash within DataGrids

### ISSUE THREAD

**Issue by phanxgames** [phanxgames/AetherStory#102]
### Environment
- Client Version: 

### Database Occurrences
1.  4160, 4159, 4158, 4157

### Description
Using the arrow keys within (or after) a DataGrid component causes a null exception in the key listener.

### Stack
>TypeError: Error #1009
>>	at feathers.controls.supportClasses::DataGridDataViewPort/calculateNavigationDestination()
>>   at feathers.controls::DataGrid/nativeStage_keyDownHandler()

**Comment by phanxgames** [comment]
Appears to only occur after using the selection dialog (cook book, or telepad?).  Then using your keyboard in any future datagrid there after.

**Comment by phanxgames** [comment]
the close menu server command client-handler is most likely the culprit

**Comment by phanxgames** [comment]
Should be fixed in next build: 356

**Comment by phanxgames** [comment]
Related #46

**Comment by phanxgames** [comment]
A crash occurred while interacting with Bank Storage.

Need help reproducing the crash.

**Comment by CharlesIV** [comment]
Has not been reported in over a year
