### ISSUE TITLE
When typing in the message window the input field loses focus after pressing Enter

### ISSUE THREAD

**Issue by rogersm** [phanxgames/AetherStory#104]
**Describe the bug**

When typing in the message window the input field loses focus after pressing Enter having to click in the field again to capture the focus and continue typing.

**To Reproduce**

1. On the message window click on the input field to get the focus.
2. Write something and press enter.
3. Input field loses focus.
4. If you press I you get the inventory window (or M for the map)

**Expected behavior**

Input field should not lose focus so you can continue typing messages.

**Screenshots**

No screenshots.

**Context:**
 - Character Name: Aldair
 - OS: MacOS
 - Patch Version: 0.3.89
 - Game Build: Alpha Version 358

**Additional context**

No additional context.

**Comment by CharlesIV** [comment]
I would say this is less of a bug, and more of an intentional design. Hitting the 'T' or 'Enter' key will also focus the chat input and allow you to type in chat. If I am misunderstanding your bug report, or if you'd like to suggest this as a feature let me know.
