### ISSUE TITLE
Memory Leak: Changing Characters and Changing Maps (back and forth)

### ISSUE THREAD

**Issue by phanxgames** [phanxgames/AetherStory#106]
**Describe the bug**
Memory usage reports are still too high. It appears there is no longer crashing relating to running out of memory at least. But the leak needs to be made under control.  
It could be related to switching characters, or questing.

**Details Found**
When changing characters, teleporting and transitioning between maps the garbage collector is not able to recover memory, and the game's memory footprint increases each time.

**Additional Info May Be Needed**
Testers please test the game with Task Manager open and watch what activities jump memory up.
Keep in mind memory climbing is normal, but it should be garbage collected and remain relatively small. When watching be sure to see if it doesn't go back down to a reasonable level shortly before logging it as a problem area.
Note: changing maps forces the memory to be garbage collected, which can be a good way to force it.

**Comment by dariojorge** [comment]
![image](https://user-images.githubusercontent.com/6954727/91361644-b3077880-e7f0-11ea-80c7-ed73d3f896fe.png)

In the tests i did i got this by using the 3 in order, transitions > teleports and character change
when i tried just character change the memory normalized with no problem even spamming the character change, the same for the transition and teleport so far i only got this by performing the 3. 
I did not tested each individually in length as it can be a slow process is it  to make the memory climb, to speed the process the 3 of them quickly get the memory to climb.

**Comment by CharlesIV** [comment]
Should be fixed
