### ISSUE TITLE
UI-Jumping when track/untrack other quests

### ISSUE THREAD

**Issue by DruidVerjin** [phanxgames/AetherStory#112]
Like in the gif when you select a quest from the objective tracker and want to track another quest, then it jumps automatically back to the original selected one.

![Jumping UI](https://user-images.githubusercontent.com/49834309/95009987-41f48580-0626-11eb-8331-2a6e57e64e31.gif)

**Comment by CharlesIV** [comment]
Some clarification notes:
This occurs from clicking on a tracked quest on the top right and not when opening the journal via the menu/"J". The selection is jumping back to the quest that was clicked in order to open the journal.

**Comment by CharlesIV** [comment]
Fixed in next patch
