### ISSUE TITLE
Question of Trivia Spirit out of the box 

### ISSUE THREAD

**Issue by DruidVerjin** [phanxgames/AetherStory#113]
**Describe the bug**
When talking to the Trivia Spirit and you get the question which is on the attachment, then the text is not in the box. 
There should be a line break. 

**Expected behavior**
A line break at Domhan Forest. 

**Screenshots**

![image](https://user-images.githubusercontent.com/49834309/95010350-e5df3080-0628-11eb-9edb-ee437bce9ff8.png)

**Context:**
 - Character Name: Verjin
 - OS: Windows 10

**Comment by CharlesIV** [comment]
![image](https://user-images.githubusercontent.com/24666944/95221685-b6b1f600-07c5-11eb-91e0-e405bc24f390.png)
![image](https://user-images.githubusercontent.com/24666944/95221733-bf0a3100-07c5-11eb-8fa9-bfc0c3ddf57f.png)
