### ISSUE TITLE
storage lag

### ISSUE THREAD

**Issue by jessespy2** [phanxgames/AetherStory#115]
**Describe the bug**
the storage takes a few secconds to update i thought i deleted my item

**To Reproduce**
1. While interacting with bank
2. Click on deposit
3. Wait
4. See item appear 3 secs later

**Expected behavior**
items disapear for a few secconds making it feel like item is in limbo/deleted to new players

**Screenshots**

**Context:**
 - Character Name: adiviah
 - OS: windows 8
 - Patch Version: 0.3.94
 - Game Build: donno

**Additional context**
may misslead new players and panic them for a sec

**Comment by CharlesIV** [comment]
Thank you for your report. This is most likely caused by your connection latency with the server. I will close this report and reopen if others also notice large delays between interactions.
