### ISSUE TITLE
I got in combat with an invisible monster

### ISSUE THREAD

**Issue by dcduncanson** [phanxgames/AetherStory#117]
**Describe the bug**
I got in combat with an invisible monster

**To Reproduce**
I was walking around and got in combat randomly

**Expected behavior**
I assume that the monster spawned before the graphic appeared on the map

**Screenshots**
None sowie

**Context:**
 - Character Name: Derry
 - OS: Windows
 - Patch Version: Winter Fest launch
 - Game Build: Winter Fest launch
 
**Additional context**
None

**Comment by CharlesIV** [comment]
Fixed 0.3.108
