### ISSUE TITLE
Battle not ending due to dead party member logging in

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#129]
**Describe the bug**
One player dies in their own battle, but when they log back in their in a battle with their party member, but since that member is in battle, they cant die properly and end battle.

**Expected behavior**
Dead players shouldn't join other battles, see #126

**Screenshots**

**Context:**
 - Patch Version: 0.3.102
 - Game Build: 397

**Comment by phanxgames** [comment]
Has this been resolved?

**Comment by CharlesIV** [comment]
Confirm fixed
