### ISSUE TITLE
Cutscene "Cannot interact with that right now"

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#132]
**Describe the bug**
Running over a cutscene trigger with a monster watching you triggers the "Cannot interact with that right now" message, stopping your movement in the process. Occurs even when a cutscene is no longer "valid" and hasn't been removed yet.

**To Reproduce**
1. Create a new player
2. Go to the shipwreck entrance cutscene
3. Lure a monster and walk onto the cutscene trigger

**Expected behavior**
1. The invalid cutscene should be removed and not trigger the message.
2. Should a cutscene have priority over a monster? (For immersion I would say yes, but you could avoid a monster battle)

**Context:**
 - Patch Version: 0.3.110
 - Game Build: 424

**Additional context**

**Comment by phanxgames** [comment]
Should be fixed in next update.
