### ISSUE TITLE
Gold amount not updating in menu

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#133]
**Describe the bug**
Gold amount does not update in menu for all transactions

**To Reproduce**
1. Be in a merchant menu
2. Have someone offer to trade
3. Complete a trade with gold
4. Gold doesnt update in menu

**Expected behavior**
Your gold amount in the menu should update whenever any kind of trade/transaction is made.

**Context:**
 - Patch Version: 0.3.110
 - Game Build: 424

**Comment by phanxgames** [comment]
is 4. main menu or merchant menu?

**Comment by phanxgames** [comment]
Solution: make trade not allowed when in merchant, or make trade close the merchant menu.

**Comment by phanxgames** [comment]
Duplicate , see #172
