### ISSUE TITLE
EXP bar stays at 0% after combat

### ISSUE THREAD

**Issue by Erktech** [phanxgames/AetherStory#134]
After killing an enemy and being rewarded EXP, the EXP bar does not update. 

Also, I know that you're still working on combat so I'm sorry if I Jumped the gun and this is not a working feature yet.

**Comment by phanxgames** [comment]
The level cap is level 5 at the moment. Is your character level 5?

**Comment by Erktech** [comment]
Yes I'm level 5.  Thanks lol.
