### ISSUE TITLE
Game crashed after combat

### ISSUE THREAD

**Issue by Erktech** [phanxgames/AetherStory#135]
### Environment - Windows 10
- Client Version: Patch 0.3.113 (build 434)

### Database Occurrences
1.  I'm not sure what to put here to be honest.
![crashscreen](https://user-images.githubusercontent.com/74945568/105443066-85ecb400-5c30-11eb-9935-8d600732c100.png)

### Description
The game crashed immediately after I clicked 'Okay' to collect my rewards for my victory in combat. 
### Stack
>

**Comment by phanxgames** [comment]
Thank you for letting me know and informing me directly in discord.
This has been a frustrating bug. But I believe it is addressed in the patch just released moments ago.
