### ISSUE TITLE
Sound cutting out

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#136]
**Describe the bug**
Sound cuts off completely at certain volume settings, randomly turning back on at times. 

**To Reproduce**
1. Open settings
2. Set volume levels as seen in screenshot

**Expected behavior**
Volume should not cut out at any volume level combination

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/109363902-a6c1ae00-785b-11eb-838d-e46e20c3e1c3.png)

**Context:**
 - Character Name: Eric
 - Patch Version: 0.3.123
 - Game Build: 451

**Additional context**
Similar to issue #29

**Comment by phanxgames** [comment]
This is a result of multiplication in the volume formula. I will need help with this.

Base volume of some music is 0.2; add your master volume control and then your music volume control:  ` 0.2 * 0.1 * 0.1 = 0.002 => rounded 0`

**Comment by CharlesIV** [comment]
This is the equation that I use for my sound engine which i'm quite happy with:
`masterVolume*musicVolume*2/(masterVolume+musicVolume)`,
 you can try adding your baseVolume like so:
`masterVolume*musicVolume*2/(masterVolume+musicVolume+1-baseVolume)` 

basically in my version it takes the average of the master and music volumes and then divides the product by the average. You do need to watch out that the denominator never is 0, which is easy enough to see if master volume == 0 then set volume to 0 instead. Then the denominator will never be 0

**Comment by CharlesIV** [comment]
Should be fixed in next patch
