### ISSUE TITLE
Character Selection/Creation screen issues

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#138]
**Describe the bug**
The character screen does not update correctly to show what options are being selected:

*Creation*
1. Hitting "New Character" doesn't show the random new character unless you change the class.
2. Hitting "Random" doesn't show the random new character unless it changes the class.
3. Unable to use arrow keys to change the character name. (Defaults to option menu)
4. After logging out, cannot type a name after clicking in the Character Name textbox. (Have to generate a random name first)

*Selection*

5. Clicking on a different character does not update the preview of the character
6. Logging out sometimes does not show your character list. (Logging out and back in fixes it)

**To Reproduce**
- Should be self explanatory, but can elaborate if needed.

**Expected behavior**
The menus to update correctly and be user friendly.

**Screenshots**

**Context:**
 - Character Name: Charles
 - OS: Windows 10
 - Patch Version: 0.3.123
 - Game Build: 451

**Additional context**
Could optimize menu as suggested in #114 
Random name generator has crashed in the past, Bug Log: 4262

**Comment by phanxgames** [comment]
Should be fixed in next update.

**Comment by CharlesIV** [comment]
Bug 6 will be worked on in bug: #166
