### ISSUE TITLE
UI not completely restored after using Medallion 

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#139]
**Describe the bug**
After using the medallion to start the quest, only your health/man/xp bar reappears. After changing map, taking damage, (state update?) it re-appears

**To Reproduce**
1. Go the the wolf cave
2. Pick up and use the medallion
3. Notice that the UI hasn't fully re-appeared

**Expected behavior**
The UI to be completely restored.

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/107108814-da835800-6808-11eb-9b15-91c395cece1d.png)

**Context:**
 - Character Name: Charles
 - OS: Windows 10
 - Patch Version: 0.3.123
 - Game Build: 451

**Comment by phanxgames** [comment]
Should be fixed in the next update.
