### ISSUE TITLE
Monsters phasing through objects

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#140]
**Describe the bug**
"I don't know if its intended or not, but I tried to get on the other side of this chest to avoid battle from the crab(safe spot) and it just went right through the chest and got me anyways. Should mobs move through chests?"

**To Reproduce**
1. Go to location in screenshot
2. See if monster goes through the chest

**Expected behavior**
Monsters should have collision with chests

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/107108851-4665c080-6809-11eb-94ff-342dea1d84be.png)

**Context:**
 - Character Name: Eric
 - Patch Version: 0.3.123
 - Game Build: 451

**Comment by phanxgames** [comment]
Should be fixed next update.
