### ISSUE TITLE
Party Bugs: v0.4.0

### ISSUE THREAD

**Issue by miniboc** [phanxgames/AetherStory#141]
**Describe the bug**
1. Party member stays in battle after dcing
2. Party member takes damage in battle after dcing
3. Party member gains exp even when dced
4. Party member blocked from logging back in after dcing if still in party. The party leader must disband party or restart server to fix

**Context:**
 - Character Name: [Miniboc]
 - OS: [e.g. Windows]
 - Patch Version: [e.g. 0.40]
 - Game Build: [e.g. 454]

**Comment by phanxgames** [comment]
Party member takes damage and dies, but logs back in with some health.

**Comment by CharlesIV** [comment]
Every "10" seconds we run a check so player doesnt get stuck in a battle with a dead monster
--Monster died when the player couldnt be sent victory, causing a server error

**Comment by phanxgames** [comment]
Original 1-4 issues above are resolved and need testing in the next patch.
Did not fix issue 1 and 2. These are acceptable.

However issue 5 : "Party member takes damage and dies, but logs back in with some health." 
needs more information gathered.

**Comment by CharlesIV** [comment]
Since the original issues will be fixed in the next patch, I will be closing this bug report and separating issue 5 into its own issue.
