### ISSUE TITLE
After dying in battle, player still has some health after relogging

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#146]
**Describe the bug**
Party member takes damage and dies, but logs back in with some health.

**To Reproduce**
1. Unknown

**Expected behavior**
A player to remain dead.

**Context:**
 - OS: Windows
 - Patch Version: 0.4.0
 - Game Build: 454

**Comment by phanxgames** [comment]
Will close because it does not contain enough information. Feel free to reopen.
