### ISSUE TITLE
Journal does not have a scrollbar

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#155]
**Describe the bug**
When you having more quests than can fit in the journal window, it overflows without a scrollbar

**To Reproduce**
1. Have at least 10 quests in your journal

**Expected behavior**
There to be a scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/113023797-090c1800-9154-11eb-9549-06dcc2234c39.png)

**Context:**
 - Patch Version: 0.4.4
 - Game Build: 464

**Comment by celojevic** [comment]
This has been fixed
