### ISSUE TITLE
Combat double arms

### ISSUE THREAD

**Issue by Ravavyr** [phanxgames/AetherStory#159]
**Describe the bug**
During combat when attacking it looks like another set of arms is doing the attack swings.
At the end of combat during the dance it shows 4 arms. 

**To Reproduce**
- go into combat 

**Expected behavior**
- not having 4 arms

**Screenshots**
none right now, just ask me. 

**Context:**
 - Character Name: ravavwin

**Comment by CharlesIV** [comment]
This was due to the animations not being made to fit the Dizwin model for the April Fools day event. Since this was a temporary event, this issue will be resolved when the normal player model is returned.
