### ISSUE TITLE
Game becoming unstable- Glitching graphics

### ISSUE THREAD

**Issue by Weemee** [phanxgames/AetherStory#160]
**Describe the bug**
Ok, multiple parts:
I looted a water bucket outside the command hall and the character animation went crazy, see link.

I relogged, hoping it would go away (which it did), but on the character select screen I had no visuals of my characters

Once I was back in, I walked around for about 10 seconds and used the telporter to "Domhan Forest" and was met with a black screen.

**To Reproduce**
I can't reproduce this sadly

**Expected behavior**
Not having my character animation glitch out whilst playing
Seeing my characters on character select screen
Not having a black screen after teleporting

**Screenshots**
Glitching animation: https://gyazo.com/6b98d8fea4ad1a032bfb71e00536a080
Black screen: https://gyazo.com/0e1c9e00efc3974a9aa7cf1c76c7d61f

**Context:**
 - Character Name: Weemee
 - OS: Windows 10
 - Patch Version: 0.4.8
 - Game Build: 480

**Additional context**
If possible, check session time and see if there's an relation there [based on comment]

**Comment by iClaimThisName** [comment]
Same thing happened to me, the cause is still unknown though.

**Comment by CharlesIV** [comment]
This is due to the game being in a corrupt or crashing state. Something in the game has become unstable. Relogging would not fix this. This could be related to the game's memory leak bug.

Player vanishing during battle is probably related:
![image](https://user-images.githubusercontent.com/24666944/114276623-6bd39e00-99f5-11eb-9dd5-39d861dc4526.png)

**Comment by CharlesIV** [comment]
The characters not appearing on character screen may not be related, so it will be put into it's own bug report: #166

**Comment by phanxgames** [comment]
Fixed. See #142
