### ISSUE TITLE
Cave/cellar lighting in interior map

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#164]
**Describe the bug**
When in an interior map, the lighting is sometimes like that from inside a cave or cellar.

**To Reproduce**
"Currently, in the Domhan outpost, every time I enter the shop with Shopkeeper Brian, lighting is fine...and entering the cellar beneath it doesn't change this if I go back up...however, if I enter that cellar, exit it on the beach near the dock, re-enter it quickly, and then go back up into the potions shop, I get cellar-style lighting with lots of strong shadows instead of the normal lighting."

**Expected behavior**
Lighting to be correct on each map/sub-map

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/114276368-4eea9b00-99f4-11eb-8ada-00f82079afc5.png)

**Context:**
 - Character Name: Andy
 - OS: MacOS
 - Patch Version: 0.4.9

**Additional context**
May be only on MacOS

**Comment by celojevic** [comment]
Fixed
