### ISSUE TITLE
Instances not resetting

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#167]
**Describe the bug**
"if the player who starts the battle dies, than teleports using the death message (50gold) before the end of ostara's speech; the instance gets bugged, ostara staying there forever & Todd not showing up anymore. we tried to quit parties to join a new instance, it didn't work as the old one isn't deleted/dismissed/reset. so we can't do todd anymore. if we talk to ostara we get teleported back to the entrance, but nothing changes."

**To Reproduce**
1. See description and notes

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/114277358-d76b3a80-99f8-11eb-94e4-69f8c6825170.png)

**Context:**
 - Character Name: audioL
 - OS: Windows
 - Patch Version: 0.9.4
 - Game Build: 484

**Additional context**
EDIT : what i wrote above might not make sense. it might be granady who went & talked to ostara (while i was in the death screen menu/chat) because he was able to move. & talking to her might've broke the instance. further tests are needed
EDIT 2 : after discussing a bit & splitting parties, & stuff, granady was the one with the bugged instance, so the first EDIT might be the real problem. (disable interactions with ostara would fix it myb?)
EDIT 3 : a suggestion to completly fix bugs similar to this one ; completly restrict player movements (if possible) when starting the battle, give them the possibilty to move again after getting tped back to the entrance. (OUT OF BATTLE) the players can move when Todd is beaten , the movement restriction start when todd dissappears.

**Comment by phanxgames** [comment]
Should be fixed in next server update.
