### ISSUE TITLE
Fully Gemmed Alpha goal does not stay complete

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#177]
**Describe the bug**
The "Fully Gemmed" Alpha 4 Goal does not stay completed once reached. Swapping to a gear which puts you below this goal, marks it as "not complete".

**To Reproduce**
1. Complete the goal
2. Swap gear

**Expected behavior**
It to stay completed

**Context:**
 - Character Name: Weemee
 - Patch Version: 0.4.0

**Comment by phanxgames** [comment]
Should be fixed in the next patch.
