### ISSUE TITLE
amare moss quest can not be completed

### ISSUE THREAD

**Issue by beashamone** [phanxgames/AetherStory#178]
i was searching the cave to the northeast or the lumber yard for the amare moss. she found all the moss but I could not see one of them. i walked out of the cave and walked back in now I cant pick up the moss at all even though it respawned.

**Comment by phanxgames** [comment]
Hello there. Thank you for opening a support ticket.

Please kindly let me know your character name (in-game) and your friend's character name.

You may also reach me directly in Discord.gg/phanxgames if you wish to chat in real-time about the issue.

Thank you,
Henry

**Comment by CharlesIV** [comment]
Closing due to lack of response / further reports.
