### ISSUE TITLE
Visual bug or actual stats calculation bug (equipment menu)

### ISSUE THREAD

**Issue by Weemee** [phanxgames/AetherStory#196]
**Describe the bug**
The bug is that the stat-changes when swapping gear is inaccurate, probably visually only (will check other characters), but this is on my Sage for now. Take note of your actual health (shown in your health bar) and compare it with your health stat. This is a 1:1 (one-to-one) ratio.

**To Reproduce**
1: Bring up the gear menu (hotkey 'U') (Image 1)
2: Click an equipped item which has 'Health' on it (and another item for that slot without 'Health' on it)
3: Click 'Change' in the bottom left, which brings up the equipment view for that slot (Image 2)
4: Look at the health stat (Image 0)
5: Select another item (as if you'd swap gear for that slot)
6: The 'Health' stat says it's going to change to your current health (Image 3)

**Expected behavior**
I expect the 'Health' stat to reflect the health that I see in the health bar next to my mana bar.

**Screenshots**
Image 0
![image](https://user-images.githubusercontent.com/30422441/133206167-99362484-3908-4694-943e-36ccd2d2928c.png)

Image 1
![image](https://user-images.githubusercontent.com/30422441/133205601-a82ad406-f6f8-4feb-848a-123a78e8c8c4.png)

Image 2
![image](https://user-images.githubusercontent.com/30422441/133205689-ed5908c0-1a83-4883-8212-6886cf28d2d1.png)

Image 3
![image](https://user-images.githubusercontent.com/30422441/133205728-4f4026a5-4f99-433c-a725-8874db7cf6b0.png)

**Context:**
 - Character Name: Weemee
 - OS: Win10
 - Patch Version: 0.5.6
 - Game Build: 566

**Additional context**
No additional context

**Comment by phanxgames** [comment]
Fixed
