### ISSUE TITLE
Health/Mana bar is also transparent in battle when near the edge of the map

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#200]
**Describe the bug**
When entering combat near the edge of the map, a player's health/mana bar remains transparent.

**To Reproduce**
1. Go to the edge of the map
2. Get into combat

**Expected behavior**
Players Health/Mana bar should be returned to normal opacity and then back to transparent after combat.

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/133947863-f6d52f59-d20c-473a-b242-3f27589618d6.png)

**Context:**
 - Character Name: Weemee
 - Patch Version: 0.5.6
 - Game Build: 566

**Comment by phanxgames** [comment]
Fixed
