### ISSUE TITLE
Progress shows null/800

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#203]
**Describe the bug**
Sometimes a progress count will be null

**To Reproduce**
1. Unknown

**Expected behavior**
Null should never be seen in the UI,

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/133947022-c19ed74f-cbb7-4f51-8aa7-473361246c1d.png)

**Comment by phanxgames** [comment]
This should have been fixed. Will close until it is reported again.
