### ISSUE TITLE
trading gold leads to gold loss with both players

### ISSUE THREAD

**Issue by sameluck** [phanxgames/AetherStory#210]
**Describe the bug**
after trading both players lose the gold they offered

**To Reproduce**
1.initiate trade with someone
2.both players involved in a trade add gold to it
3.confirming trade should cause a gold decrease for both players

**Expected behavior**
one player loses gold and one player gains it

**Screenshots**
none

**Context:**
 - Character Name: ---
 - OS: ---
 - Patch Version: 0.5.6
 - Game Build: 566

**Additional context**
full description as given on discord:
"found a bug exchanging gold and I lost all my and my mates gold"
"so what happened was my mate wanted to buy some gear so I traded some gold with him he also gave me a little bit so I wouldnt be without any gold so he would spend exact
but when we checked our bags. he didnt have the gold I sent him and I didnt have the amount he sent me"

**Comment by phanxgames** [comment]
Test Results for gold for gold trading:

	STARTED	
	joe	peg
	111244	88
		
	TRADED	
	joe	peg
	4	2
		
		
	EXPECTED	
	joe	peg
	111242	90
		
		
	RESULT	
	joe	peg
	111246	86
		
Conclusion: Joe's gold transfer was overwritten by peg's gold transfer.


EDIT: However, these results do not match the description by OP. They are claiming that gold is being lost. The test results do not show a net loss. If gold is actually being lost/eaten to the void, then this is a critical error. 

But I do not see that happening in my tests. In no situation does gold vanish. Only one half of the trade occurs, and the other half is safely ignored.


Need more info.

**Comment by phanxgames** [comment]
This should be fixed in the next patch.
