### ISSUE TITLE
Spells becoming bugged in battle

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#218]
**Describe the bug**
"In a multi-enemy scenario, if you spam Fireball, the spell won't be able to be casted again for the remainder of the battle. This is also true after attacking with Spectral Slash and spamming any spell that costs MP
not sure if it's from a latency issue because i am all the way in the EU"
"If you press the spell during the initial load into battle's cooldown you will also bug the spell iirc"

**To Reproduce**
1. Spam a spell when entering combat

**Expected behavior**
Spells should not become locked up

**Context:**
 - Character Name: Alexthehuman2

**Comment by phanxgames** [comment]
Start of combat spamming of abilities should no longer cause issues as of the next patch.
The first part of the issue requires more investigation.

**Comment by phanxgames** [comment]
Fixed
