### ISSUE TITLE
Clipping of text in credentials box

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#220]
**Describe the bug**
The bottom half of text is being clipped in the credentials box on occasions.

**To Reproduce**
1. Unknown

**Expected behavior**
Text should not be clipped.

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/140676518-0b5bbe9a-f1f0-48e1-a203-c900660f7003.png)

**Context:**
 - Character Name: Weemee

**Additional context**
Full screen mode was in use.

**Comment by phanxgames** [comment]
Issue with AIR runtime most likely.
