### ISSUE TITLE
AetherStory (Not Responding) 

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#226]
**Describe the bug**
After clicking on the Quest: Hungry Adventuring, the UI page failed to load correctly.

**To Reproduce**
1. Unknown

**Expected behavior**
Menus should load correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/140682280-49d2260c-04ed-4f20-bce8-ad225f36a4ed.png)

**Context:**
 - Character Name: Belleina

**Comment by phanxgames** [comment]
Could not reproduce.
