### ISSUE TITLE
Idle Disconnect Not Working - Can Stay logged in Forever

### ISSUE THREAD

**Issue by phanxgames** [phanxgames/AetherStory#231]
**Describe the bug**
Can Stay logged in Forever. Even though it is suppose to disconnect you after going AFK for 20 minutes.

**To Reproduce**
1. Log in
2. Go AFK
3. Stay online forever

**Expected behavior**
Disconnect after 20 minutes of AFK.

**Comment by CharlesIV** [comment]
Henry made boo boo and made a duplicate #211
