### ISSUE TITLE
Paying death does not regenerate energy

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#232]
**Describe the bug**
When a player is revived, their health and mana is set to full but their energy is not. 

**To Reproduce**
1. Die. 
2. Pay death
3. Go back into battle

**Expected behavior**
This could be an intend feature, but a player has suggested that it feels inconsistent to not set their energy to full.

**Context:**
 - Character Name: Loli Power

**Comment by phanxgames** [comment]
Added.
