### ISSUE TITLE
[Press Space] showing when you cannot interact with an entity

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#233]
**Describe the bug**
[Press Space] shows up for a player when they are unable to interact with an entity from a particular side of it.

**To Reproduce**
1. Go to the tree in the screenshot (on a player that hasn't looted it)
2. Stand behind it
3. Attempt to loot it

**Expected behavior**
[Press Space] should not show if the player cannot actually interact with an entity.

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/141509539-e6a31cb4-07ce-418f-9245-2903c8f62883.png)

**Context:**
 - Character Name: LoliPower
 - Patch Version: 0.5.28
 - Game Build: 624

**Comment by celojevic** [comment]
Standing behind the tree and looting it works as expected
