### ISSUE TITLE
Character creation rotation effects all character's rotation

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#234]
**Describe the bug**
When rotating a character in the character creation screen, leaving it (hitting back or completing character creation) you will see that the rotation is applied to whatever character is selected.

**To Reproduce**
1. log in
2. open a new char creation
3. rotate the model
4. go back
5. your existing char is rotated

**Expected behavior**
Character rotation should reset when exiting the character creation screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/141510544-38871266-4ff1-4ed0-8af7-fa368cfe6730.png)

**Comment by celojevic** [comment]
Fixed and can close issue @CharlesIV
