### ISSUE TITLE
Incorrect stats info

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#235]
**Describe the bug**
A player equipping a piece of equipment shows it's going to increase a stat to one value. After equipping, it shows that their stat has increased twice what it should have. (There may be other issues, but this is what was reported)

**To Reproduce**
1. Just follow my video

**Expected behavior**
Stat's info should be accurate and not cause confusion

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://youtu.be/aaWO7husqMs)

**Context:**
 - Character Name: Charles / LoliPower
 - OS: Windows 10
 - Patch Version: 0.5.28
 - Game Build: 624

**Additional context**

**Comment by celojevic** [comment]
This bug has been fixed and this issue can be closed @CharlesIV
