### ISSUE TITLE
Client memory leak while over encumbered

### ISSUE THREAD

**Issue by Meisaka** [phanxgames/AetherStory#236]
**Describe the bug**
walking around while over encumbered and getting the message on screen will cause the client to leak memory.

**To Reproduce**
1. Pick up enough items to become encumbered (201/200 is okay for example)
2. Walk around so the "you are over encumbered" message shows
3. The client can reach 1+ GB of system RAM usage after about 7-10 minutes of constant walking.

**Expected behavior**
Walking while over encumbered should not leak memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/5482813/142295285-c7ffe705-cb37-4da5-b144-4c2a02a6f2a5.png)

**Context:**
 - Character Name: Meisaka
 - OS: Windows 10 Pro
 - Patch Version: 0.5.29
 - Game Build: 627

**Additional context**
This only happens while over the encumbered weight threshold *and* walking around getting the message.
Seems largely related to the __message appearing__, other testing includes:
- standing still while over encumbered does not leak memory.
- walking around while under the weight limit does not appear to leak memory
- allowing the client to run and hit 2GB+ can lead to effects similar to #92

**Comment by CharlesIV** [comment]
Should be fixed
