### ISSUE TITLE
Can't Use Skill Slots Beyond First Two for Abilities or the E item slot

### ISSUE THREAD

**Issue by VRNocturne** [phanxgames/AetherStory#237]
**Describe the bug**
On the character build screen, I can click on any of the slots for abilities, but when trying to do the actual assignment, the game does not respond nor communicates to the player why the skill can't be slotted.

This occurred when trying to use both item slots as well as slot my 2nd spell (3rd ability).

**To Reproduce**
1. While interacting with character build screen (Esc -> Build)
2. Click on an empty ability slot while having 2 abilities and one item equipped on your slots
3. Try to slot in the item or ability (as applicable). For example, I tried to slot my Healing Spring in slot 3.
4. The game did not slot Healing Spring in slot 3, nor did it tell me why it could not be slotted.

**Expected behavior**
I expected to ability to be slotted in the location I selected.

**Context:**
 - Character Name: Nocta
 - OS: Windows
 - Patch Version: 0.5.25
 - Game Build: current (idk the exact number or where to find it in the game)

**Comment by CharlesIV** [comment]
These slots should not be selectable

**Comment by celojevic** [comment]
The unusable slots are now locked and no longer selectable as per update 0.6.11. This issue can be closed
