### ISSUE TITLE
Sprites overlapping incorrectly

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#24]
Please comment any sprites that are not being rendered correctly on their "z" level (y-sort) here.

**Comment by CharlesIV** [comment]
![image](https://user-images.githubusercontent.com/24666944/78675375-f5b4cc80-78b2-11ea-988f-f950b4546dd0.png)

**Comment by phanxgames** [comment]
I guess we will keep this open for future reports related to this?

**Comment by CharlesIV** [comment]
![unknown](https://user-images.githubusercontent.com/24666944/80853301-b94c6600-8bfd-11ea-9df5-2b7d8979fee5.png)

**Comment by CharlesIV** [comment]
![unknown](https://user-images.githubusercontent.com/24666944/82106075-dea49e00-96ec-11ea-86a5-2c0098cccb85.png)

**Comment by CharlesIV** [comment]
Transferred to Trello
