### ISSUE TITLE
Hitting escape in Inn Menu doesnt hide gold hud

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#253]
**Describe the bug**
When interacting with an Inn keeper, if instead of choosing an option you hit ESC, the gold hud will remain behind.

**To Reproduce**
1. Go to Inn
2. Talk to Inn keeper
3. Hit escape

**Expected behavior**
Gold hud should be hidden when using ESC.

**Screenshots**
![image](https://user-images.githubusercontent.com/24666944/148499018-c8d3a92a-5284-4b4a-b1de-39f11b6985de.png)

Misc. Info
I did try this same method on the #153 bug and could not replicate.

**Comment by phanxgames** [comment]
Fixed.
