### ISSUE TITLE
Unable to leave a party in special case.

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#39]
Accepting a party invite of someone who has gone offline puts you in the party. (Intended?) However you are unable to leave the party by using /leave due to: "You are not in a party." Relogging does correct this. Inviting the player back into the party (when they're back online) also corrects this. Connected bug: #40 

/disband does not work since the player is not the party leader

**Comment by phanxgames** [comment]
fixed with #39
