### ISSUE TITLE
Unable to reconnect after logging off during a party invite

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#40]
After inviting someone to a party, you log out. The player then accepts the invite. Attempting to log back in results in a Error Object:object. The player who accepted the invite can use /leave in order to fix this. Connected bug: #39

**Comment by CharlesIV** [comment]
sending data: 100`chk:2c7f4f821d3866b290a5814bd73a4bb4,mess:D5btfg5tSqOrnshPiBXbDF6QcUu4eU6RZWfSt6d1VR6XaIf0C8PS8r7DH7ongCLP,aid:602`Dn8Q
inc: Dn8Q`{"error":{},"para":null}

**Comment by phanxgames** [comment]
fixed.
