### ISSUE TITLE
Texture Jitter / Warping on Fullscreen (and other scaled resolutions)

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#66]
Texture's that are not normally visible jitter into view on occasion. (May be due to low framerate? Needs testing)

![lumberyard_logpile](https://user-images.githubusercontent.com/24666944/86875798-553c9700-c0b1-11ea-8406-7536f5b41288.png)

**Comment by phanxgames** [comment]
Playing the game at non-standard resolutions, including fullscreen or a resized window, can also lend its hand at rendering issues such as this.  When trying to reproduce attempt at various screen sizes.

**Comment by phanxgames** [comment]
Revealed original screenshot was playing in fullscreen.

Thus the problem is:
Textures not rounding to the nearest pixel when the rendered is scaled.

Solution: unknown at this point

**Comment by phanxgames** [comment]
Will probably not be able to fix this without a massive rewrite of the rendering engine.
