### ISSUE TITLE
Minimap Flickering

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#75]
### Environment
- Client Version: 0.3.336
- OS: Windows 10

### Description
When walking around, "randomly" the minimap will flicker black. After reviewing the trace on scout from multiple runs, each run had the "GAME RENDERER:: CULLING" trace within the last second of the minimap flicker.

**Comment by phanxgames** [comment]
I saw this finally on another computer in my house (not my computer), its very strange. I have no idea what is causing it. Needs more input to narrow it down.

**Comment by CharlesIV** [comment]
Fixed in Patch 0.3.85+
