### ISSUE TITLE
[Press Enter] disappearing.

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#77]
### Environment
- Client Version: 0.3.336
- OS: Windows 10

### Description
[Press Enter] is disappearing. Both Rebecca and Charles have experienced this bug.

**Comment by phanxgames** [comment]
Can you figure out what is causing it? Steps to reproduce please.

**Comment by iClaimThisName** [comment]
[Press Space] disappears when people are chatting when you log in. 

Has been reproduced twice using these steps:
1. Get someone else to type/spam in the in-game chat
2. Log in (whilst said person is using the chat)
3. [Press Space] should be gone and only reappear when you log out and/or re-open the game (NOTE:

**Comment by CharlesIV** [comment]
Fixed 0.3.85+
