### ISSUE TITLE
No XP for baking a large amount

### ISSUE THREAD

**Issue by XVOMercy** [phanxgames/AetherStory#85]
**Describe the bug**
When you purchase [I am assuming] a large amount of supplies and craft all of them in a crafting station [when cooking] you do not gain the XP for the craft.

**To Reproduce**
1. Purchase 53 yeast
2. Purchase 53 flour
3. Go into the crafting station
4. Craft all
5. Get no XP!

**Expected behavior**
You to gain the XP along with the baked bread

**Screenshots**
![image](https://user-images.githubusercontent.com/26396642/89410958-9d6fc900-d6f2-11ea-9657-d213e9ec21fe.png)
As you can see, I have 53 missing XP but I crafted 53 bread [Ignore how it says 66, that was just my other baked bread]
![image](https://user-images.githubusercontent.com/26396642/89411039-bd06f180-d6f2-11ea-800e-9d0efc999af5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Unrelated, but Firefox.
 - Version Alpha 3

**Additional context**
Do I get a refund? That costed me like 400 gold. Am sad.

**Comment by phanxgames** [comment]
You cannot gain EXP from a Level 1 recipe when you are Level 3.
