### ISSUE TITLE
Meadery Beedicament Quest shows wrong popup on quest start

### ISSUE THREAD

**Issue by AaronSolent** [phanxgames/AetherStory#87]
**Describe the bug**
The 4th Step of the "Meadery Beedicament" Quest shows the wrong popup objective.

**To Reproduce**
As far as I can tell, just start the "Collect 8 Goldenrod Petals" step of the quest. I have a clip of the bug below, I can't see that I did anything special.

The Objective reads "Pets Collected: 1 / 8", which I assume is for a separate quest

**Expected behaviour**
In my case, the Objective should likely read "Petals Collected: 0 / 8"

**Screenshots**
[Video Clip of Bug](https://youtu.be/Jqh46RKgXbw)

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10

**Additional context**
Overseer says other objective popups on the quest were wrong too, but I only have a clip of the objective

**Comment by phanxgames** [comment]
Fixed.
Confirm in the next patch 0.3.82 + 
(to be published in the next 24 hours)
