### ISSUE TITLE
Quantity select popup incorrect incrementation 

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#88]
**Describe the bug**
When hitting the plus/minus on a quantity select popup, the quantity changes by increments of 10, or to the quantity available if the max is less than 10. Typing a number in between values of 0 and 10 rounds them.

**To Reproduce**
1. Go to Settings.
2. Change the Fullscreen setting under Graphics to the other option not currently selected.
3. Walk up to a merchant, buy/sell an item, and change the quantity selected.

**Expected behavior**
The quantity to change by increments of 1 and there not to be any rounding.

**Screenshots**

**Desktop:**
 - OS: Windows 7, Windows 10
 - Version 0.3.338

**Comment by phanxgames** [comment]
Fixed.
Confirm in 0.3.82 +
