### ISSUE TITLE
In Main Menu Lv [level] [class] changes between level and locations

### ISSUE THREAD

**Issue by iClaimThisName** [phanxgames/AetherStory#89]
**Describe the bug**
When you open the main menu, to the right of your character name it is supposed to say Lv [level] [class] (for example: Lv 5 Sage). The bug (?) is that it swaps between that message, the map your on and area you're in (for example, Lv 5 Sage, Domhan Coast, Meadows). Charles suggested it might be a feature for parties (so you can see where your party members are) but the only one it swaps for is yourself. On the party members it just says their level and class.

**To Reproduce**
1. Join the game
(1.5. Join a party or invite someone to your party)
2. Press esc

**Expected behavior**
When not in a party, it says Lv [level] [class] and when in a party, ONLY for the party members it swaps between their level and class, and their location.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 0.3.338

**Comment by phanxgames** [comment]
I agree that having to rotate between this information is annoying, especially when you want to see one bit of information and you have to wait for the others to rotate past.  

The intention was to have the 3 bits of information rotate through for everyone, including yourself, and the people in your party.  If that is how it works, please confirm. Then this bug can be closed.

If you have a suggestion on how to improve displaying all that information, let me know. But at this time, we simply don't have enough room to show it all.

**Comment by phanxgames** [comment]
Realized what the bug was and Fixed.
