### ISSUE TITLE
Spotlight Render Background using wrong texture

### ISSUE THREAD

**Issue by phanxgames** [phanxgames/AetherStory#94]
**Describe the bug**
Happens after playing the game for a few hours, and going AFK for 10 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/5034306/89590973-0cded900-d817-11ea-974e-f107e840457b.png)

**Comment by phanxgames** [comment]
Cannot reproduce.

Could be a result of DX11 Windows Full Screen optimizations:

Support article steps:
Right click the game -> properties -> compatibility -> disable fullscreen optimizations

Needs further testing.

**Comment by phanxgames** [comment]
Going to close this until it gets reported again. I think it is isolated to one player's computer/hardware environment.

**Comment by CharlesIV** [comment]
Another player reported it happening after "I bought an item from the merchant and then it disappeared but there is still the "Press Space" and the light there is no more light and the animation of the character is stuck on the one we see on the image".

**Comment by phanxgames** [comment]
This appears to be a result of the user using integrated graphics and/or running out of ram.  Its been identified as an issue with the run time that our game uses which is out of our control. Will close as we can't do anything to fix it.
