### ISSUE TITLE
Spamming Menu Causes Odd Behaviors

### ISSUE THREAD

**Issue by phanxgames** [phanxgames/AetherStory#96]
**Describe the bug**
Spamming Menu Causes Odd Behaviors

**Screenshots**
![image](https://user-images.githubusercontent.com/5034306/89636209-41ce4880-d876-11ea-938d-30eb6876be7a.png)

**Comment by phanxgames** [comment]
This should have been fixed. Please confirm.

**Comment by iEnvyU** [comment]
In my testing i was spamming "esc" "m" "b" "i", and it crashed my game 08/27/2020 1:05am

**Comment by phanxgames** [comment]
Should be fixed in next build, 359+
