### ISSUE TITLE
Player's hp/mana doesn't update in party list upon lvl up

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#97]
**Describe the bug**
A player's hp/mana does not update in a party list when they level up. Logging out and back in updates it.

**To Reproduce**
1. Join a party.
2. Level up

**Expected behavior**
The player's hp/mana should update in the party list automatically.

**Context:**
 - Character Name: Delphine, Mackensie, Krystina
 - OS: Windows
 - Patch Version: 0.3.81
 - Game Build: 0.3.337

**Comment by phanxgames** [comment]
Was this resolved with the recent fixes to hp/mp in battles? Please confirm.

**Comment by phanxgames** [comment]
Was this resolved? Please confirm.
