### ISSUE TITLE
Spamming 'play character' button can crash the game

### ISSUE THREAD

**Issue by iClaimThisName** [phanxgames/AetherStory#99]
**Describe the bug**
When I accidentally pressed 'play character' twice in a row, it gave me an error message, something along the lines of Error: already logged in from another location (don't know for sure, I only got this one once and didn't write it down)
Upon further investigation I got 5 more outcomes of the same steps (clicking the 'play character' button multiple times in a row):
-Gets stuck on loading screen
-Game crashes
-Doesn't do anything? (so stays on the character selection screen)
-Error: NOAUTH
-Can't join the game at all...

**To Reproduce**
1. Open the game and login to your account normally
2. Select a character and press 'play character' 2 or more times in quick succession

**Expected behavior**
Join the game as usual.

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/69261909/89718179-4ea98400-d9bd-11ea-9681-350b4e0a1130.png)

**Context:**
 - Character Name: Rebecca
 - OS: Windows 10
 - Patch Version: 0.3.82
 - Game Build: 399

**Additional context**
I'm sorry :(

**Comment by phanxgames** [comment]
Fixed In server hotfix.
